<?php
/**
 * @file
 * Main file of the module Drupal publisher publisher.
 */

/**
 * Implements hook_menu().
 */
function dc_publisher_menu() {
  $items = array();

  $items['admin/apps/%dc_apps/documentation'] = array(
    'title' => 'Documentation',
    'description' => 'View documentation of an app',
    'access arguments' => array('view documentation'),
    'page callback' => 'dc_publisher_documentation',
    'page arguments' => array(2),
  );

  $items['publisher'] = array(
    'title' => 'Publisher',
    'description' => 'Supplying JSON information for an app',
    'access callback' => 'dc_publisher_oatuh_allowed',
    'page callback' => 'dc_publisher_supply_information',
  );

  $items['dc/connect'] = array(
    'title' => 'Connect',
    'description' => 'Allow to pull information from user',
    'access callback' => 'dc_publisher_oatuh_allowed',
    'page callback' => 'dc_publisher_connect_with',
  );

  $items['apps/%dc_apps/user_approve_app'] = array(
    'title' => 'Approve app',
    'description' => 'Allow to user approve app',
    'access callback' => 'dc_publisher_user_approve_app_access',
    'access arguments' => array(1),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dc_publisher_user_approve_app', 1),
  );

  $items['user/%user/apps'] = array(
    'title' => 'Apps',
    'description' => 'Manage your approved apps',
    'access arguments' => array('manage approved apps'),
    'page callback' => 'dc_publisher_manage_apps',
    'page arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_entity_info().
 */
function dc_publisher_entity_info() {
  return array(
    'approved_apps' => array(
      'label' => t('Approved app'),
      'entity class' => 'DrupalPublisherApprovedApp',
      'controller class' => 'EntityAPIController',
      'base table' => 'approved_apps',
      'entity keys' => array(
        'id' => 'id',
      ),
      'load hook' => '',
    ),
  );
}

/**
 * Create Drupal publisher approved app entity.
 *
 * @param $data
 *  Initialize data of the Drupal publisher app.
 *
 * @return DrupalPublisherApprovedApp
 *  Initialized object a Drupal publisher approved app.
 */
function dc_publisher_approved_apps_create($data = array()) {
  global $user;

  $data += array(
    'uid' => $user->uid,
    'timestamp' => REQUEST_TIME,
  );

  return entity_create('approved_apps', $data);
}

/**
 * Load multiple Drupal publisher approved app entity.
 *
 * @param $ids
 *  Array of Drupal publisher apps IDs.
 *
 * @return DrupalPublisherApprovedApp[]
 *  Array of Drupal publisher approved apps objects.
 */
function dc_publisher_approved_apps_load_multiple($ids) {
  return entity_load('approved_apps', $ids);
}

/**
 * Load a single Drupal publisher approved app entity.
 *
 * @param $id
 *  Id a Drupal publisher app entity.
 *
 * @return DrupalPublisherApprovedApp
 *  Drupal publisher approved apps object.
 */
function dc_publisher_approved_apps_load($id) {
  $entity = entity_load('approved_apps', array($id));
  return reset($entity);
}

/**
 * Delete multiple Drupal publisher approved app entities.
 *
 * @param $ids
 *  List of Drupal publisher app IDs to delete.
 */
function dc_publisher_approved_apps_delete_multiple($ids) {
  entity_delete_multiple('approved_apps', $ids);
}

/**
 * Implements hook_entity_delete().
 */
function dc_publisher_entity_delete($entity, $type) {
  if ($type != 'dc_app') {
    return;
  }

  // TODO: Do. http://www.youtube.com/watch?v=Ra70O9nps6E
}

/**
 * Return the basic address of the the site oauth publisher page.
 */
function dc_publisher_base_url() {
  global $base_url;

  return $base_url . '?q=publisher';
}

/**
 * When oatuh want to pull data he need to pass the oauth signature test.
 */
function dc_publisher_oatuh_allowed() {
  global $base_url;

  if (!isset($_GET['key']) || !isset($_GET['secret'])) {
    return;
  }

  $reader = new DrupalConnect($_GET['key'], $_GET['secret']);
  $reader
    ->SetUrl(dc_publisher_base_url())
    ->SetOauthRequest();

  return $reader->VerifySignature($_GET['signature']);
}

/**
 * Page callback - supply the information the oauth service selected.
 */
function dc_publisher_supply_information() {
  $app = dc_apps_load_by_keys($_GET['key'], $_GET['secret']);

  if (!$app) {
    // No app found - return nothing.
    drupal_json_output(t("App with the key and secret wasn't found"));
  }

  if (!in_array($_GET['data'], array_keys($app->need))) {
    drupal_json_output(t("The @data information you selected cannot be supplied due to app settings.", array('@data' => $_GET['data'])));
    exit();
  }

  // Start the query.
  $query = new entityFieldQuery();
  $query->entityCondition('entity_type', $_GET['data']);

  // When searching for users and the checkbox was checked only users which
  // approve the app will be display in the search results.
  if (variable_get('apps_search_for_users_limit', FALSE) && $_GET['data'] == 'user') {
    // Adding tag for altering query later on.
    $query->addTag('DrupalPublisherOnlyApprovedUsers');
  }

  // Find the field to work upon and the operator to apply.

  // Display in batches.
  $result_number = variable_get('apps_data_number', 25);
  $page = !empty($_GET['page']) ? $_GET['page'] * $result_number : 1;
  $query->range($page, $result_number);

  // Execute.
  $result = $query->execute();

  if (empty($result[$_GET['data']])) {
    drupal_json_output(t('No data were found according to you search curatorial.'));
  }

  // Supply the information.
  drupal_json_output(entity_load($_GET['data'], array_keys($result[$_GET['data']])));
}

/**
 * A client asked to connect with a user - supply the information about the
 * user.
 */
function dc_publisher_connect_with() {
  global $user;

  $app = dc_apps_load_by_keys($_GET['key'], $_GET['secret']);

  // Check that user is logged in.
  if (!user_is_logged_in()) {
    // Redirect the user for logging in.
  }

  if (!dc_apps_user_approved_apps($app)) {
    // Redirect the user to approve the app.
  }

  drupal_json_output($user);
}

/**
 * Implements hook_permission().
 */
function dc_publisher_permission() {
  return array(
    'view documentation' => array(
      'title' => t('View documentation'),
      'description' => t('Allow to the user watch the documentation of an app.'),
    ),
    'manage approved apps' => array(
      'title' => t('Manage user own apps'),
      'description' => t('Allow to user manage his approved apps.'),
    ),
  );
}

/**
 * Implements hook_dc_apps_generate_links_action_alter().
 */
function dc_publisher_dc_apps_generate_links_action_alter(&$actions, DrupalConnectApps $app) {
  $actions['documentation'] = array(
    'title' => t('Documentation'),
    'href' => 'admin/apps/' . $app->id . '/documentation',
  );
}

/**
 * Implements hook_dc_apps_app_options_alter().
 */
function dc_publisher_dc_apps_app_options_alter(&$items, DrupalConnectApps $app) {
  $items[] = $app->generateLink('documentation');
}

/**
 * Display documentation for an app.
 */
function dc_publisher_documentation(DrupalConnectapps $app) {
  $reader = new DrupalConnect($app->app_key, $app->app_secret);
  $reader
    ->SetUrl(dc_publisher_base_url())
    ->SetOauthRequest()
    ->SetSignatureParameter();

  $urls = array();

  foreach (array_keys($app->need) as $entity) {
    $entity_reader = clone $reader;
    $entity_reader->request->set_parameter('data', $entity);

    $urls[] = l($entity, $entity_reader->getUrl());
    $entity_reader->request->unset_parameter('data');
  }

  return theme('item_list', array('items' => $urls));
}

/**
 * Access callback for determine if the user can approve the app.
 */
function dc_publisher_user_approve_app_access(DrupalConnectApps $app, $account = NULL) {

  // Anonymous users are not allowed to approve any app.
  if (!user_is_logged_in()) {
    return FALSE;
  }

  // Load the current user.
  if (!$account) {
    global $user;
    $account = user_load($user->uid);
  }

  // See if the user approved this app before.
  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'approved_apps')
    ->propertyCondition('app_id', $app->id)
    ->propertyCondition('uid', $account->uid)
    ->execute();

  return empty($result['approved_apps']);
}

/**
 * Displaying the form for approving apps.
 */
function dc_publisher_user_approve_app($form, &$form_state, DrupalConnectApps $app) {
  $form_state['#entity'] = $app;

  return confirm_form($form,
    t('Are you approving @title?', array('@title' => $app->title)),
    'admin/apps',
    t('This app need your approve for accessing your information. Are you approve this operation?'),
    t('Approve'),
    t('Cancel')
  );
}

/**
 * Submit handler - user approved the app. Save it and redirect the to where
 * he came from.
 */
function dc_publisher_user_approve_app_submit($form, &$form_state) {
  global $base_url, $user;
  $form_state['redirect'] = $base_url;
  $app = $form_state['#entity'];

  $approve = dc_publisher_approved_apps_create();
  $approve->uid = $user->uid;
  $approve->app_id = $app->id;
  $approve->save();

  drupal_set_message(t('The app @name has been approved. Thank you.', array('@name' => $app->title)));
}

/**
 * Allow to user manage his apps.
 */
function dc_publisher_manage_apps($account) {
  // TODO: Cache.
  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'approved_apps')
    ->propertyCondition('uid', $account->uid)
    ->execute();

  $header = array(
    t('Application name'),
    array('data' => t('Options'), 'colspan' => 2),
  );

  $rows = array();
  if (empty($result['approved_apps'])) {
    $rows[] = array(array('data' => t('None approved apps were found'), 'colspan' => 3));
  }
  else {
    // Get the approved apps ID.
    $apps_id = array();
    $approved_apps = dc_publisher_approved_apps_load_multiple(array_keys($result['approved_apps']));
    foreach ($approved_apps as $approve) {
      $apps_id[] = $approve->app_id;
    }

    $query = new EntityFieldQuery();
    $result = $query
      ->entityCondition('entity_type', 'dc_app')
      ->propertyCondition('id', $apps_id)
      ->execute();

    $apps = dc_apps_load_multiple(array_keys($result['dc_app']));

    foreach ($apps as $app) {
      $rows[] = array($app->title, t('Edit'), t('Delete'));
    }
  }

  $content = theme('table', array('header' => $header, 'rows' => $rows));

  return $content;
}
